import test from "node:test";
import assert from "node:assert/strict";
import { CONFIG } from "../src/config.js";
import {
  canSpawnNextEvent,
  createObstacleEvent,
  eventWeightsForTime,
  isEventFair,
  ObstacleManager,
  obstacleOpacityForX,
  obstacleSinkForX,
  obstacleSpeedForTime,
  spawnDelayForTime
} from "../src/obstacles.js";

test("single events always have a valid Y position", () => {
  for (let i = 0; i < 50; i += 1) {
    const event = createObstacleEvent({ surferY: 300, elapsed: 0, random: fixedRandom([0.1, i / 50]) });
    assert.equal(event.type, "single");
    assert.equal(event.heads.length, 1);
    assertHeadInsideBounds(event.heads[0]);
  }
});

test("double events stay inside the playable region", () => {
  for (let i = 0; i < 80; i += 1) {
    const event = createObstacleEvent({
      surferY: 300,
      elapsed: 180,
      random: fixedRandom([0.99, i / 80, 0.9, 0.65, 0.25, 0.4])
    });

    if (event.type !== "double") continue;
    assert.equal(event.heads.length, 2);
    event.heads.forEach(assertHeadInsideBounds);
  }
});

test("double events generated by the factory remain fair", () => {
  for (let i = 0; i < 50; i += 1) {
    const event = createObstacleEvent({
      surferY: 270,
      elapsed: 140,
      random: fixedRandom([0.99, i / 50, 0.1, 0.7, 0.33, 0.5])
    });

    assert.equal(isEventFair(event, 270, event.speed), true);
  }
});

test("impossible candidates are rejected before a fallback is returned", () => {
  let checks = 0;
  const event = createObstacleEvent({
    surferY: CONFIG.SURF_BOUNDS.bottom,
    elapsed: 180,
    random: () => 0.5,
    validator: (candidate, surferY, speed) => {
      checks += 1;
      return checks > 3 && isEventFair(candidate, surferY, speed);
    }
  });

  assert.equal(event.attemptCount, 4);
  assert.equal(isEventFair(event, CONFIG.SURF_BOUNDS.bottom, event.speed), true);
});

test("generation has an attempt limit and safe fallback", () => {
  const event = createObstacleEvent({
    surferY: CONFIG.SURF_BOUNDS.top,
    elapsed: 180,
    random: () => 0.5,
    validator: () => false
  });

  assert.equal(event.attemptCount, 31);
  assert.equal(event.fallback, true);
  assert.equal(isEventFair(event, CONFIG.SURF_BOUNDS.top, event.speed), true);
});

test("obstacle speed never exceeds configured maximum", () => {
  assert.equal(obstacleSpeedForTime(0), CONFIG.OBSTACLE_START_SPEED);
  assert.equal(obstacleSpeedForTime(CONFIG.DIFFICULTY_RAMP_SECONDS * 5), CONFIG.OBSTACLE_MAX_SPEED);
});

test("only one obstacle event can threaten the player at once", () => {
  assert.equal(canSpawnNextEvent(null), true);
  assert.equal(canSpawnNextEvent({ threatening: true }), false);
  assert.equal(canSpawnNextEvent({ threatening: false }), true);
});

test("single and double weights stay within requested limits", () => {
  const start = eventWeightsForTime(0);
  const end = eventWeightsForTime(999);

  assert.equal(start.single, CONFIG.SINGLE_WEIGHT_START);
  assert.equal(start.double, 1 - CONFIG.SINGLE_WEIGHT_START);
  assert.equal(end.single, CONFIG.SINGLE_WEIGHT_END);
  assert.ok(end.double <= CONFIG.DOUBLE_WEIGHT_MAX);
});

test("obstacle opacity is full before the submerge start", () => {
  assert.equal(obstacleOpacityForX(CONFIG.OBSTACLE_SUBMERGE_START_X + 40), 1);
  assert.equal(obstacleOpacityForX(CONFIG.OBSTACLE_SUBMERGE_START_X), 1);
});

test("obstacle opacity decreases between submerge start and end", () => {
  const midpoint = (CONFIG.OBSTACLE_SUBMERGE_START_X + CONFIG.OBSTACLE_SUBMERGE_END_X) / 2;
  const opacity = obstacleOpacityForX(midpoint);

  assert.ok(opacity > 0);
  assert.ok(opacity < 1);
});

test("obstacle opacity reaches zero at the submerge end", () => {
  assert.equal(obstacleOpacityForX(CONFIG.OBSTACLE_SUBMERGE_END_X), 0);
  assert.equal(obstacleOpacityForX(CONFIG.OBSTACLE_SUBMERGE_END_X - 80), 0);
});

test("obstacle opacity is clamped between zero and one", () => {
  for (const x of [-500, 0, 249, 300, 390, 800, 1500]) {
    const opacity = obstacleOpacityForX(x);
    assert.ok(opacity >= 0);
    assert.ok(opacity <= 1);
  }
});

test("submerge sink is slight and reaches the configured amount", () => {
  assert.equal(obstacleSinkForX(CONFIG.OBSTACLE_SUBMERGE_START_X), 0);
  assert.equal(obstacleSinkForX(CONFIG.OBSTACLE_SUBMERGE_END_X), CONFIG.OBSTACLE_SUBMERGE_SINK_PX);
});

test("an individual submerged head is counted as dodged only once", () => {
  const manager = new ObstacleManager();
  manager.activeEvent = fakeEvent([{ x: CONFIG.OBSTACLE_SUBMERGE_END_X + 1, y: 300 }], 20);

  assert.equal(manager.update(0.1, 12, 300), 1);
  assert.equal(manager.activeEvent, null);
  assert.equal(manager.update(0.1, 12, 300), 0);
});

test("a fully submerged head is no longer collision-active", () => {
  const manager = new ObstacleManager();
  manager.activeEvent = fakeEvent([{ x: CONFIG.OBSTACLE_SUBMERGE_END_X, y: 300 }]);
  manager.activeEvent.heads[0].resolved = true;
  manager.activeEvent.heads[0].counted = true;

  assert.deepEqual(manager.hitboxes(), []);
});

test("a double event remains active until both heads are resolved", () => {
  const manager = new ObstacleManager();
  manager.activeEvent = fakeEvent([
    { x: CONFIG.OBSTACLE_SUBMERGE_END_X + 1, y: 280 },
    { x: CONFIG.OBSTACLE_SUBMERGE_START_X, y: 340 }
  ], 20);

  assert.equal(manager.update(0.1, 20, 300), 1);
  assert.notEqual(manager.activeEvent, null);

  manager.activeEvent.heads[1].x = CONFIG.OBSTACLE_SUBMERGE_END_X + 1;
  assert.equal(manager.update(0.1, 20, 300), 1);
  assert.equal(manager.activeEvent, null);
});

test("event completion permits the next spawn cycle", () => {
  const manager = new ObstacleManager();
  manager.activeEvent = fakeEvent([{ x: CONFIG.OBSTACLE_SUBMERGE_END_X + 1, y: 300 }], 20);

  manager.update(0.1, 20, 300);

  assert.equal(canSpawnNextEvent(manager.activeEvent), true);
  assert.ok(manager.spawnTimer >= CONFIG.SPAWN_DELAY_END.min);
  assert.ok(manager.spawnTimer <= CONFIG.SPAWN_DELAY_START.max);
});

test("configured spawn delays remain valid", () => {
  assert.ok(CONFIG.SPAWN_DELAY_START.min <= CONFIG.SPAWN_DELAY_START.max);
  assert.ok(CONFIG.SPAWN_DELAY_END.min <= CONFIG.SPAWN_DELAY_END.max);
  assert.ok(spawnDelayForTime(0, () => 0) >= CONFIG.SPAWN_DELAY_START.min);
  assert.ok(spawnDelayForTime(999, () => 1) <= CONFIG.SPAWN_DELAY_END.max);
});

function assertHeadInsideBounds(head) {
  assert.ok(head.y - head.height / 2 >= CONFIG.SURF_BOUNDS.top);
  assert.ok(head.y + head.height / 2 <= CONFIG.SURF_BOUNDS.bottom);
}

function fixedRandom(values) {
  let index = 0;
  return () => {
    const value = values[index % values.length];
    index += 1;
    return value;
  };
}

function fakeEvent(heads, speed = CONFIG.OBSTACLE_START_SPEED) {
  return {
    type: heads.length === 1 ? "single" : "double",
    speed,
    threatening: true,
    collided: false,
    heads: heads.map((head) => ({
      x: head.x,
      y: head.y,
      width: CONFIG.HEAD_DISPLAY_WIDTH,
      height: CONFIG.HEAD_DISPLAY_HEIGHT,
      resolved: false,
      counted: false
    }))
  };
}
