import test from "node:test";
import assert from "node:assert/strict";
import { readdir, readFile } from "node:fs/promises";
import { CONFIG } from "../src/config.js";
import {
  DODGE_OBSTACLE_TYPES,
  STANDARD_SWIMMER_VISIBLE_ALPHA_HEIGHT,
  dodgeObstacleVisibleBounds,
  getDodgeObstacleType,
  materializeDodgeObstacleGeometry,
  selectDodgeObstacleType
} from "../src/dodgeObstacles.js";
import { OBSTACLE_PATTERNS, PATTERN_BY_ID, instantiatePattern, validatePatternTuning } from "../src/obstaclePatterns.js";
import { obstacleRowCenter, obstacleRowCenters } from "../src/rowGeometry.js";
import { isSurferPositionValid } from "../src/surferGeometry.js";
import { flattenPatterns, validateObstacleTimeline, validatePatternSequence } from "../src/patternValidator.js";
import {
  canSpawnNextEvent,
  createDodgeObstacle,
  createObstacleEvent,
  DeterministicObstacleScheduler,
  eventWeightsForTime,
  hasMinimumHeadSeparation,
  isHeadVisiblyPresent,
  isEventPlacementClear,
  isEventFair,
  ObstacleManager,
  obstacleCollisionActive,
  obstacleOpacityForX,
  obstacleRenderPresentation,
  obstacleRouteProgress,
  obstacleRiseProgress,
  obstacleSinkForX,
  rowIsReleased,
  obstacleSpeedForTime,
  spawnDelayForTime
} from "../src/obstacles.js";
import { DIFFICULTY_STAGES, SWIMMER_TIERS, stageTuning } from "../src/obstacleTuning.js";

const HEAD_TYPE = getDodgeObstacleType("head");
const NOODLE_GIRL_TYPE = getDodgeObstacleType("noodle-girl");
const NOODLE_MAN_TYPE = getDodgeObstacleType("noodle-man");
const SCUBA_MAN_TYPE = getDodgeObstacleType("scuba-man");
const TUBE_GIRL_TYPE = getDodgeObstacleType("tube-girl");
const TUBE_WOMAN_TYPE = getDodgeObstacleType("tube-woman");

test("single events always have a valid Y position", () => {
  for (let i = 0; i < 50; i += 1) {
    const event = createObstacleEvent({ surferY: 300, elapsed: 0, random: fixedRandom([0.1, i / 50]) });
    assert.equal(event.type, "single");
    assert.equal(event.heads.length, 1);
    assertHeadInsideBounds(event.heads[0]);
  }
});

test("double events stay inside the playable region", () => {
  for (let i = 0; i < 80; i += 1) {
    const event = createObstacleEvent({
      surferY: 300,
      elapsed: 180,
      random: fixedRandom([0.99, i / 80, 0.9, 0.65, 0.25, 0.4])
    });

    if (event.type !== "double") continue;
    assert.equal(event.heads.length, 2);
    event.heads.forEach(assertHeadInsideBounds);
  }
});

test("double events generated by the factory remain fair", () => {
  for (let i = 0; i < 50; i += 1) {
    const event = createObstacleEvent({
      surferY: 270,
      elapsed: 140,
      random: fixedRandom([0.99, i / 50, 0.1, 0.7, 0.33, 0.5])
    });

    assert.equal(isEventFair(event, 270, event.speed), true);
  }
});

test("impossible deterministic candidates are rejected before a fallback is returned", () => {
  let checks = 0;
  const event = createObstacleEvent({
    surferY: CONFIG.SURF_BOUNDS.bottom,
    elapsed: 180,
    random: () => 0.5,
    validator: (candidate, surferY, speed) => {
      checks += 1;
      return checks > 3 && isEventFair(candidate, surferY, speed);
    }
  });

  assert.equal(event.attemptCount, 4);
  assert.equal(isEventFair(event, CONFIG.SURF_BOUNDS.bottom, event.speed), true);
});

test("generation has an attempt limit and exits safely without an unsafe fallback", () => {
  let checks = 0;
  const event = createObstacleEvent({
    surferY: CONFIG.SURF_BOUNDS.top,
    elapsed: 180,
    random: () => 0.5,
    validator: () => {
      checks += 1;
      return false;
    }
  });

  assert.equal(event, null);
  assert.equal(checks, CONFIG.HEAD_SPAWN_PLACEMENT_RETRIES);
});

test("obstacle speed never exceeds configured maximum", () => {
  assert.equal(obstacleSpeedForTime(0), CONFIG.OBSTACLE_START_SPEED);
  assert.equal(obstacleSpeedForTime(CONFIG.DIFFICULTY_RAMP_SECONDS * 5), CONFIG.OBSTACLE_MAX_SPEED);
});

test("only one obstacle event can threaten the player at once", () => {
  assert.equal(canSpawnNextEvent(null), true);
  assert.equal(canSpawnNextEvent({ threatening: true }), false);
  assert.equal(canSpawnNextEvent({ threatening: false }), true);
});

test("a head cannot spawn with rendered bounds overlapping an active head", () => {
  const event = createObstacleEvent({
    surferY: 300,
    elapsed: 0,
    activeHeads: [createTestHead(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(4))],
    random: () => 0.5,
    pattern: PATTERN_BY_ID["opening-single-low"]
  });

  assert.equal(event, null);
});

test("configured minimum visual gap is respected", () => {
  const head = createTestHead(400, 300);
  const requiredGap = dodgeObstacleVisibleBounds(head).width + head.visualGapX;
  const tooClose = createTestHead(400 + requiredGap - 0.1, 300);
  const clear = createTestHead(400 + requiredGap + 0.001, 300);

  assert.equal(hasMinimumHeadSeparation(head, tooClose), false);
  assert.equal(hasMinimumHeadSeparation(head, clear), true);
});

test("different-row swimmers use visible alpha bounds instead of arbitrary vertical padding", () => {
  const head = createDodgeObstacle(400, obstacleRowCenter(2), Math.random, HEAD_TYPE, { row: 2 });
  const adjacent = createDodgeObstacle(400, obstacleRowCenter(3), Math.random, TUBE_GIRL_TYPE, { row: 3 });
  const shiftToOverlap = dodgeObstacleVisibleBounds(head).bottom - dodgeObstacleVisibleBounds(adjacent).top - 0.1;
  const overlapping = { ...adjacent, y: adjacent.y + shiftToOverlap };

  assert.equal(hasMinimumHeadSeparation(head, adjacent), true);
  assert.equal(hasMinimumHeadSeparation(head, overlapping), false);
});

test("vertically stacked heads with insufficient space are rejected", () => {
  const row2 = createDodgeObstacle(500, obstacleRowCenter(2), Math.random, HEAD_TYPE, { row: 2 });
  const row3 = createDodgeObstacle(500, obstacleRowCenter(3), Math.random, HEAD_TYPE, { row: 3 });
  const event = fakeEvent([
    { x: row2.x, y: row2.y, type: HEAD_TYPE },
    { x: row3.x, y: row2.y + STANDARD_SWIMMER_VISIBLE_ALPHA_HEIGHT - 1, type: HEAD_TYPE }
  ]);

  assert.equal(isEventPlacementClear(event), false);
});

test("multiple heads in the same proposed event are checked against one another", () => {
  const event = fakeEvent([
    { x: 500, y: 300 },
    {
      x: 500 + row2VisibleWidth() + CONFIG.HEAD_MIN_VISUAL_GAP_X - 1,
      y: 300
    }
  ]);

  assert.equal(isEventPlacementClear(event), false);
});

test("visible fading or submerging heads continue to reserve spawn space", () => {
  const activeHead = createTestHead(500, 300);
  activeHead.x = CONFIG.OBSTACLE_SUBMERGE_START_X - 1;
  activeHead.resolved = false;
  const event = fakeEvent([{ x: activeHead.x, y: activeHead.y }]);

  assert.equal(obstacleOpacityForX(activeHead.x) > 0, true);
  assert.equal(isHeadVisiblyPresent(activeHead), true);
  assert.equal(isEventPlacementClear(event, [activeHead]), false);
});

test("resolved heads still reserve space while they remain visible", () => {
  const activeHead = createTestHead(CONFIG.OBSTACLE_SUBMERGE_START_X - 1, 300);
  activeHead.resolved = true;
  const event = fakeEvent([{ x: activeHead.x, y: activeHead.y }]);

  assert.equal(obstacleOpacityForX(activeHead.x) > 0, true);
  assert.equal(isHeadVisiblyPresent(activeHead), true);
  assert.equal(isEventPlacementClear(event, [activeHead]), false);
});

test("fully resolved and invisible heads no longer reserve spawn space", () => {
  const activeHead = createTestHead(CONFIG.OBSTACLE_SUBMERGE_END_X, 300);
  activeHead.resolved = true;
  const event = fakeEvent([{ x: activeHead.x, y: activeHead.y }]);

  assert.equal(obstacleOpacityForX(activeHead.x), 0);
  assert.equal(isHeadVisiblyPresent(activeHead), false);
  assert.equal(isEventPlacementClear(event, [activeHead]), true);
});

test("ordinary obstacle placement stays on shared rows when retried", () => {
  const event = createObstacleEvent({
    surferY: 300,
    elapsed: 0,
    activeHeads: [createTestHead(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(1))],
    random: fixedRandom([0.1, 0, 0, 0])
  });

  assert.notEqual(event, null);
  assert.equal(obstacleRowCenters().includes(event.heads[0].y), true);
  assert.equal(Number.isInteger(event.heads[0].row), true);
  assert.equal(isEventPlacementClear(event, [createTestHead(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(1))]), true);
});

test("no valid placement leaves no unintended partial group in the manager", () => {
  const manager = new ObstacleManager();
  manager.spawnTimer = 0;
  manager.update(0.01, 0, 300, {
    activeHeads: createBlockingSpawnColumn()
  });

  assert.equal(manager.activeEvent, null);
});

test("the navigable-path rule still rejects unfair obstacle layouts", () => {
  const surferY = midpoint(CONFIG.SURF_BOUNDS.top, CONFIG.SURF_BOUNDS.bottom);
  const playerX = CONFIG.SURF_BOUNDS.left + (CONFIG.SURF_BOUNDS.right - CONFIG.SURF_BOUNDS.left) * 0.35;
  const event = fakeEvent([{ x: playerX + 1, y: surferY }], 999);

  assert.equal(isEventFair(event, surferY, event.speed), false);
});

test("single and double weights stay within requested limits", () => {
  const start = eventWeightsForTime(0);
  const end = eventWeightsForTime(999);

  assert.equal(start.single, CONFIG.SINGLE_WEIGHT_START);
  assert.equal(start.double, 1 - CONFIG.SINGLE_WEIGHT_START);
  assert.equal(end.single, CONFIG.SINGLE_WEIGHT_END);
  assert.ok(end.double <= CONFIG.DOUBLE_WEIGHT_MAX);
});

test("runtime source does not reference obsolete dodge assets", async () => {
  const sourceFiles = await sourceFilePaths();
  const contents = await Promise.all(sourceFiles.map((path) => readFile(path, "utf8")));
  const obsoleteDodgeAssets = [
    ["assets/", "head", ".png"].join(""),
    ["assets/", "dodge", "-tube", ".png"].join("")
  ];

  assert.equal(contents.some((content) => obsoleteDodgeAssets.some((asset) => content.includes(asset))), false);
});

test("dodge obstacle registry includes the current active dodge sprites", () => {
  assert.deepEqual(
    DODGE_OBSTACLE_TYPES.map((type) => type.assetKey).sort(),
    [
      "dodge-head",
      "dodge-noodle-girl",
      "dodge-noodle-man",
      "dodge-scuba-man-water",
      "dodge-tube-girl",
      "dodge-tube-woman"
    ]
  );
  assert.deepEqual(
    DODGE_OBSTACLE_TYPES.map((type) => type.file).sort(),
    [
      "dodge-head.png",
      "dodge-noodle-girl.png",
      "dodge-noodle-man.png",
      "dodge-scuba-man-water.png",
      "dodge-tube-girl.png",
      "dodge-tube-woman.png"
    ]
  );
  assert.equal(DODGE_OBSTACLE_TYPES.every((type) => type.spawnWeight === 1), true);
});

test("scuba is explicitly registered as a reusable riser presentation", () => {
  assert.deepEqual(SCUBA_MAN_TYPE.presentation, {
    type: "riser",
    riserAssetKey: "dodge-scuba-man-riser",
    surfacedAssetKey: "dodge-scuba-man-water",
    startRouteProgress: 0.15,
    endRouteProgress: 0.37,
    collisionActivationProgress: 0.85,
    travelHeightRatio: 1
  });
  assert.deepEqual(SCUBA_MAN_TYPE.assetFiles, [
    { assetKey: "dodge-scuba-man-riser", file: "dodge-scuba-man-riser.png" },
    { assetKey: "dodge-scuba-man-water", file: "dodge-scuba-man-water.png" }
  ]);
});

test("normal swimmers do not opt into riser presentation", () => {
  for (const type of DODGE_OBSTACLE_TYPES.filter((type) => type.id !== "scuba-man")) {
    assert.equal(type.presentation, null, type.id);
    assert.deepEqual(type.assetFiles, [{ assetKey: type.assetKey, file: type.file }]);
  }
});

test("each registered dodge obstacle keeps its own dimensions, spacing, and collision data", () => {
  const seenIds = new Set();
  const seenAssets = new Set();

  for (const type of DODGE_OBSTACLE_TYPES) {
    assert.ok(type.id);
    assert.ok(type.assetKey);
    assert.ok(type.file.endsWith(".png"));
    assert.ok(type.render.width > 0);
    assert.ok(type.render.height > 0);
    assert.ok(type.hitbox.width > 0);
    assert.ok(type.hitbox.height > 0);
    assert.ok(type.source.width > 0);
    assert.ok(type.source.height > 0);
    assert.ok(type.alpha.width > 0);
    assert.ok(type.alpha.height > 0);
    assert.ok(type.alpha.x >= 0);
    assert.ok(type.alpha.y >= 0);
    assert.ok(type.alpha.x + type.alpha.width <= type.source.width);
    assert.ok(type.alpha.y + type.alpha.height <= type.source.height);
    assert.ok(type.visualGap.x > 0);
    assert.equal(seenIds.has(type.id), false);
    assert.equal(seenAssets.has(type.assetKey), false);
    seenIds.add(type.id);
    seenAssets.add(type.assetKey);
  }
});

test("standard dodge obstacles render from an explicit visible-alpha target without changing centers", () => {
  for (const type of DODGE_OBSTACLE_TYPES) {
    const expectedHeight = STANDARD_SWIMMER_VISIBLE_ALPHA_HEIGHT / (type.alpha.height / type.source.height);
    const expectedWidth = expectedHeight * (type.source.width / type.source.height);
    const obstacle = createDodgeObstacle(420, obstacleRowCenter(3), Math.random, type, { row: 3 });
    const manager = new ObstacleManager();
    const ctx = new FakeContext();
    manager.activeEvent = fakeEventFromObstacles([obstacle]);

    manager.draw(ctx, { dodgeObstacles: { [type.assetKey]: image(type.assetKey) } });

    assertAlmostEqual(obstacle.width, expectedWidth);
    assertAlmostEqual(obstacle.height, expectedHeight);
    assertAlmostEqual(ctx.drawnWidth, expectedWidth);
    assertAlmostEqual(ctx.drawnHeight, expectedHeight);
    assert.equal(ctx.drawnX + ctx.drawnWidth / 2, obstacle.x);
    assert.equal(ctx.drawnY + ctx.drawnHeight / 2, obstacle.y);
    assert.equal(obstacle.y, obstacleRowCenter(3));
    assert.equal(dodgeObstacleVisibleBounds(obstacle).height, STANDARD_SWIMMER_VISIBLE_ALPHA_HEIGHT);
  }
});

test("standard dodge collision bounds scale with the rendered alpha bounds", () => {
  for (const type of DODGE_OBSTACLE_TYPES) {
    const obstacle = createDodgeObstacle(420, obstacleRowCenter(2), Math.random, type, { row: 2 });
    const expectedVisible = dodgeObstacleVisibleBounds(obstacle);

    assertAlmostEqual(obstacle.collisionWidth, expectedVisible.width);
    assertAlmostEqual(obstacle.collisionHeight, expectedVisible.height);
    assert.equal(obstacle.hitboxScaleX, type.hitbox.scaleX);
    assert.equal(obstacle.hitboxScaleY, type.hitbox.scaleY);
    assert.ok(obstacle.collisionWidth * obstacle.hitboxScaleX < expectedVisible.width);
    assert.ok(obstacle.collisionHeight * obstacle.hitboxScaleY < expectedVisible.height);
  }
});

test("weighted dodge obstacle selection returns only registered types deterministically", () => {
  assert.equal(selectDodgeObstacleType(() => 0).id, "head");
  assert.equal(selectDodgeObstacleType(() => 0.16).id, "head");
  assert.equal(selectDodgeObstacleType(() => 0.17).id, "noodle-girl");
  assert.equal(selectDodgeObstacleType(() => 0.33).id, "noodle-girl");
  assert.equal(selectDodgeObstacleType(() => 0.34).id, "noodle-man");
  assert.equal(selectDodgeObstacleType(() => 0.49).id, "noodle-man");
  assert.equal(selectDodgeObstacleType(() => 0.5).id, "scuba-man");
  assert.equal(selectDodgeObstacleType(() => 0.66).id, "scuba-man");
  assert.equal(selectDodgeObstacleType(() => 0.67).id, "tube-girl");
  assert.equal(selectDodgeObstacleType(() => 0.83).id, "tube-girl");
  assert.equal(selectDodgeObstacleType(() => 0.84).id, "tube-woman");
  assert.equal(selectDodgeObstacleType(() => 0.99).id, "tube-woman");
});

test("ordinary obstacle spawning uses authored deterministic obstacle types", () => {
  const pattern = PATTERN_BY_ID["opening-pair-wide"];
  const event = createObstacleEvent({ surferY: 300, elapsed: 0, pattern, difficultyStage: 0 });

  assert.deepEqual(event.heads.map((head) => head.obstacleTypeId), ["head", "tube-woman"]);
  assert.deepEqual(event.heads.map((head) => head.assetKey), ["dodge-head", "dodge-tube-woman"]);
});

test("a normal fairness-validated pattern can spawn noodle-man", () => {
  const pattern = PATTERN_BY_ID["stage2-sweeping-staircase"];
  const event = createObstacleEvent({ surferY: 300, elapsed: 0, pattern, difficultyStage: 2 });

  assert.notEqual(event, null);
  assert.equal(event.patternId, "stage2-sweeping-staircase");
  assert.deepEqual(event.heads.map((head) => [head.row, head.obstacleTypeId, head.assetKey, head.timeOffset]), [
    [3, "noodle-man", "dodge-noodle-man", 0]
  ]);
  assert.equal(isEventFair(event, 300, event.speed), true);
  assert.equal(isEventPlacementClear(event), true);
});

test("row geometry calculates exactly six centers inside the playable bounds", () => {
  const centers = obstacleRowCenters();

  assert.equal(centers.length, 6);
  assert.deepEqual(centers, [211.25, 263.75, 316.25, 368.75, 421.25, 473.75]);
  assert.equal(centers.every((y) => y > CONFIG.SURF_BOUNDS.top && y < CONFIG.SURF_BOUNDS.bottom), true);
});

test("ordinary pattern library exposes deliberate tiered row patterns", () => {
  assert.ok(OBSTACLE_PATTERNS.length >= 12);
  assert.deepEqual(PATTERN_BY_ID["center-gate"].obstacles.map((obstacle) => obstacle.row), [0, 1, 4, 5]);
  assert.equal(PATTERN_BY_ID["diagonal-weave"].safeRoute.includes("diagonal"), true);
  assert.equal(PATTERN_BY_ID["dense-finale"].allowOverlap, true);
});

test("authored pattern tuning references valid stages, rows, and pattern IDs", () => {
  const result = validatePatternTuning();

  assert.deepEqual(result.errors, []);
  assert.equal(result.valid, true);
});

test("authored normal swimmer patterns never spawn more than two swimmers at one timestamp", () => {
  for (const pattern of OBSTACLE_PATTERNS) {
    assert.ok(maxSimultaneousSwimmers(pattern) <= 2, pattern.id);
  }
});

test("scheduled tier 1-3 swimmer patterns never spawn more than two swimmers at one timestamp", () => {
  for (const tier of Object.values(SWIMMER_TIERS)) {
    for (const patternId of tier.schedule) {
      assert.ok(maxSimultaneousSwimmers(PATTERN_BY_ID[patternId]) <= 2, patternId);
    }
  }
});

test("tier 1-3 deterministic schedule order remains authored", () => {
  assert.deepEqual(SWIMMER_TIERS[1].schedule, [
    "opening-single-low",
    "opening-single-high",
    "opening-pair-wide",
    "opening-gate-top",
    "opening-gate-bottom",
    "opening-single-center"
  ]);
  assert.deepEqual(SWIMMER_TIERS[2].schedule, [
    "stage1-alternating-openings",
    "stage1-same-row-follow",
    "stage1-high-low",
    "stage1-low-high",
    "stage1-diagonal"
  ]);
  assert.deepEqual(SWIMMER_TIERS[3].schedule, [
    "stage2-staggered-diagonal",
    "stage2-sweeping-staircase",
    "stage2-split-clusters",
    "stage2-dense-gate",
    "stage2-long-weave"
  ]);
});

test("every scheduled tier 1 pattern creates and validates at runtime", () => {
  for (const patternId of SWIMMER_TIERS[1].schedule) {
    const event = createObstacleEvent({
      surferY: 300,
      elapsed: 0,
      pattern: PATTERN_BY_ID[patternId],
      difficultyTier: 1
    });

    assert.notEqual(event, null, patternId);
    assert.equal(event.patternId, patternId);
    assert.equal(isEventFair(event, 300, event.speed), true, patternId);
    assert.equal(isEventPlacementClear(event), true, patternId);
  }
});

test("deterministic scheduler repeats the same stage sequence after reset", () => {
  const first = sampleScheduledEvents();
  const second = sampleScheduledEvents();

  assert.deepEqual(first, second);
  assert.equal(first.every((event) => stageTuning(0).schedule.includes(event.patternId)), true);
});

test("stage 2 deterministic schedule keeps noodle-man reachable after cooler fallback", () => {
  const first = sampleStageEvents(2, 5);
  const second = sampleStageEvents(2, 5);

  assert.deepEqual(first, second);
  assert.deepEqual(first.map((event) => event.patternId), [
    "stage2-staggered-diagonal",
    "stage2-sweeping-staircase",
    "stage2-split-clusters",
    "stage2-dense-gate",
    "stage2-long-weave"
  ]);
  assert.deepEqual(first[1].heads, [
    ["noodle-man", "dodge-noodle-man", 3, 0]
  ]);
});

test("post-encounter stage 2 manager path resumes normal swimmers and reaches noodle-man", () => {
  const manager = new ObstacleManager();
  const spawned = [];

  manager.spawnTimer = 0;
  manager.update(0.01, 120, 300, { difficultyStage: 2 });
  spawned.push(manager.activeEvent);
  resolveActiveEvent(manager);
  manager.update(0.01, 121, 300, { difficultyStage: 2 });
  manager.update(stageTuning(2).spawnDelaySeconds, 122, 300, { difficultyStage: 2 });
  spawned.push(manager.activeEvent);

  assert.deepEqual(spawned.map((event) => event.patternId), [
    "stage2-staggered-diagonal",
    "stage2-sweeping-staircase"
  ]);
  assert.equal(spawned[1].heads.some((head) => head.assetKey === "dodge-noodle-man"), true);
});

test("scheduled tier 1-3 patterns are runtime-valid with actual dodge sprite geometry", () => {
  for (const stage of [0, 1, 2]) {
    for (const patternId of stageTuning(stage).schedule) {
    const event = createObstacleEvent({
      surferY: 300,
      elapsed: 0,
      pattern: PATTERN_BY_ID[patternId],
      difficultyStage: stage
    });

    assert.notEqual(event, null, patternId);
    assert.equal(event.patternId, patternId);
    assert.equal(isEventFair(event, 300, event.speed), true, patternId);
    assert.equal(isEventPlacementClear(event), true, patternId);
  }
  }
});

test("no gameplay RNG changes ordinary obstacle schedule", () => {
  const scheduler = new DeterministicObstacleScheduler();
  const event = scheduler.nextEvent({
    difficultyStage: 0,
    surferY: 300,
    activeHeads: []
  });

  assert.equal(event.patternId, "opening-single-low");
  assert.deepEqual(event.heads.map((head) => [head.row, head.obstacleTypeId]), [[4, "head"]]);
});

test("stage row release tuning is centralized", () => {
  assert.deepEqual(DIFFICULTY_STAGES.map((stage) => stage.releaseProgress), [1, 0.6, 0.5]);
  assert.deepEqual(DIFFICULTY_STAGES.map((stage) => stage.maxActivePerRow), [1, 2, 2]);
  assert.equal(DIFFICULTY_STAGES[0].rowRelease, "fade");
});

test("stage 0 row release waits for actual fade", () => {
  const head = createTestHead(500, obstacleRowCenter(2));
  head.row = 2;
  assert.equal(rowIsReleased(2, [head], stageTuning(0)), false);

  head.x = CONFIG.OBSTACLE_SUBMERGE_START_X;
  assert.equal(rowIsReleased(2, [head], stageTuning(0)), true);
});

test("stage 1 and stage 2 release rows by normalized route progress", () => {
  const head = createTestHead(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2));
  head.row = 2;
  head.x = head.routeStartX - (head.routeStartX - head.routeEndX) * 0.59;

  assert.equal(rowIsReleased(2, [head], stageTuning(1)), false);
  head.x = head.routeStartX - (head.routeStartX - head.routeEndX) * 0.6;
  assert.equal(rowIsReleased(2, [head], stageTuning(1)), true);

  head.x = head.routeStartX - (head.routeStartX - head.routeEndX) * 0.5;
  assert.equal(rowIsReleased(2, [head], stageTuning(2)), true);
  assert.equal(obstacleRouteProgress(head), 0.5);
});

test("stage row limits prevent unintended same-row stacking", () => {
  const first = createTestHead(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2));
  const second = createTestHead(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING - 20, obstacleRowCenter(2));
  first.row = 2;
  second.row = 2;

  assert.equal(rowIsReleased(2, [first], stageTuning(0)), false);
  assert.equal(rowIsReleased(2, [first, second], stageTuning(1)), false);
});

test("ordinary dodge sprites spawn only in defined rows", () => {
  for (let i = 0; i < 20; i += 1) {
    const event = createObstacleEvent({
      surferY: 300,
      elapsed: 120,
      random: fixedRandom([0.9, i / 20, 0, 0.5, 0.25, 0.75])
    });

    assert.ok(event.heads.length >= 1);
    assert.equal(event.heads.every((head) => obstacleRowCenters().includes(head.y)), true);
    assert.equal(event.heads.every((head) => Number.isInteger(head.row)), true);
  }
});

test("scaled dodge objects preserve lane coordinates and generated navigable gaps", () => {
  assert.deepEqual(obstacleRowCenters(), [211.25, 263.75, 316.25, 368.75, 421.25, 473.75]);

  for (let i = 0; i < 18; i += 1) {
    const event = createObstacleEvent({
      surferY: obstacleRowCenter(i % CONFIG.OBSTACLE_ROW_COUNT),
      elapsed: 0,
      random: fixedRandom([0.1, (i % 3) / 3, 0, (i % DODGE_OBSTACLE_TYPES.length) / DODGE_OBSTACLE_TYPES.length])
    });

    assert.notEqual(event, null);
    assert.equal(event.heads.every((head) => head.y === obstacleRowCenter(head.row)), true);
    assert.equal(isEventFair(event, obstacleRowCenter(i % CONFIG.OBSTACLE_ROW_COUNT), event.speed), true);
  }
});

test("valid two-row gate pattern is accepted by the fairness validator", () => {
  const pattern = instantiatePattern(PATTERN_BY_ID["center-gate"], { mirror: false });
  const result = validatePatternSequence([{ pattern }], {
    speed: CONFIG.OBSTACLE_START_SPEED,
    surferY: midpoint(CONFIG.SURF_BOUNDS.top, CONFIG.SURF_BOUNDS.bottom)
  });

  assert.equal(result.valid, true);
});

test("all standard swimmers fit every authoritative obstacle row by visible alpha", () => {
  const spacing = obstacleRowCenters()[1] - obstacleRowCenters()[0];

  for (const type of DODGE_OBSTACLE_TYPES) {
    for (const row of [0, 1, 2, 3, 4, 5]) {
      const obstacle = createDodgeObstacle(420, obstacleRowCenter(row), Math.random, type, { row });
      const bounds = dodgeObstacleVisibleBounds(obstacle);

      assert.ok(bounds.top >= CONFIG.SURF_BOUNDS.top, `${type.id} row ${row} top`);
      assert.ok(bounds.bottom <= CONFIG.SURF_BOUNDS.bottom, `${type.id} row ${row} bottom`);
      assert.ok(bounds.height <= spacing, `${type.id} row ${row} height`);
    }
  }
});

test("minimum two-row openings are visibly passable while one-row openings are not", () => {
  const requiredOpening = CONFIG.SURFER_DISPLAY_HEIGHT * CONFIG.SURFER_HITBOX_SCALE_Y +
    CONFIG.PATTERN_VALIDATION_PADDING * 2;
  const twoRowWall = [0, 1, 4, 5].map((row) =>
    createDodgeObstacle(420, obstacleRowCenter(row), Math.random, HEAD_TYPE, { row })
  );
  const oneRowWall = [0, 1, 2, 4, 5].map((row) =>
    createDodgeObstacle(420, obstacleRowCenter(row), Math.random, HEAD_TYPE, { row })
  );

  assert.ok(largestVisibleOpening(twoRowWall) >= requiredOpening);
  assert.ok(largestVisibleOpening(oneRowWall) < requiredOpening);
});

test("pattern validation materializes authored obstacle type geometry", () => {
  const pattern = instantiatePattern(PATTERN_BY_ID["opening-single-center"]);
  const [obstacle] = flattenPatterns([{ pattern }], CONFIG.OBSTACLE_START_SPEED);
  const tubeGirl = materializeDodgeObstacleGeometry("tube-girl");

  assert.equal(obstacle.typeId, "tube-girl");
  assert.equal(obstacle.obstacleTypeId, "tube-girl");
  assert.equal(obstacle.collisionHeight, tubeGirl.collisionHeight);
  assert.notEqual(obstacle.collisionWidth, materializeDodgeObstacleGeometry("head").collisionWidth);
});

test("a wall with only one usable row is rejected", () => {
  const obstacles = [0, 1, 2, 4, 5].map((row) =>
    createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(row), Math.random, HEAD_TYPE, { row })
  );

  assert.equal(validateObstacleTimeline(obstacles, { speed: CONFIG.OBSTACLE_START_SPEED, surferY: obstacleRowCenter(3) }).valid, false);
});

test("valid diagonal route is accepted and too-fast diagonal route is rejected", () => {
  const pattern = instantiatePattern(PATTERN_BY_ID["diagonal-weave"], { mirror: false });
  const routePlayerX = 420;
  const compressedPattern = {
    ...pattern,
    id: "compressed-diagonal-weave",
    obstacles: pattern.obstacles.map((obstacle) => ({
      ...obstacle,
      timeOffset: obstacle.timeOffset * 0.12
    }))
  };
  const valid = validatePatternSequence([{ pattern }], {
    speed: CONFIG.OBSTACLE_START_SPEED,
    surferY: obstacleRowCenter(5),
    playerX: routePlayerX
  });
  const tooFast = validatePatternSequence([{ pattern: compressedPattern }], {
    speed: CONFIG.OBSTACLE_START_SPEED,
    surferY: obstacleRowCenter(5),
    playerX: routePlayerX
  });

  assert.equal(isSurferPositionValid(routePlayerX, valid.safeRoute.at(-1).ys[0]), true);
  assert.equal(valid.valid, true);
  assert.equal(tooFast.valid, false);
});

test("fairness validator samples surfer positions through authoritative movement geometry", () => {
  const obstacle = createTestHead(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(3));
  const impossibleMovementConfig = {
    ...CONFIG,
    SURFER_MOVEMENT_FOOTPRINT: [
      { x: -1000, y: -1000 },
      { x: 1000, y: -1000 },
      { x: 1000, y: 1000 },
      { x: -1000, y: 1000 }
    ]
  };

  const result = validateObstacleTimeline([obstacle], {
    config: impossibleMovementConfig,
    speed: CONFIG.OBSTACLE_START_SPEED,
    surferY: obstacleRowCenter(3)
  });

  assert.equal(result.valid, false);
  assert.equal(result.reason, "no-legal-positions");
});

test("overlapping patterns are rejected when their combined route is blocked", () => {
  const topGate = instantiatePattern(PATTERN_BY_ID["two-row-gate-top"], { mirror: false });
  const bottomGate = instantiatePattern(PATTERN_BY_ID["two-row-gate-bottom"], { mirror: false });
  const result = validatePatternSequence([
    { pattern: topGate, startTime: 0 },
    { pattern: bottomGate, startTime: 0 }
  ], {
    speed: CONFIG.OBSTACLE_START_SPEED,
    surferY: midpoint(CONFIG.SURF_BOUNDS.top, CONFIG.SURF_BOUNDS.bottom)
  });

  assert.equal(result.valid, false);
});

test("cosmetic bobbing does not change collision row alignment", () => {
  const manager = new ObstacleManager();
  manager.addObstacle({
    assetKey: "bottle",
    x: 500,
    row: 2,
    width: 60,
    height: 30,
    speed: 100,
    collisionScale: 0.5,
    bobAmount: 20
  });
  const before = manager.hitboxes()[0];

  manager.update(0.5, 10, 300);
  const after = manager.hitboxes()[0];

  assert.equal(before.y, after.y);
  assert.equal(manager.encounterObstacles[0].y, obstacleRowCenter(2));
});

test("spawned obstacles retain their selected type during update, collision, and draw", () => {
  for (const type of DODGE_OBSTACLE_TYPES) {
    const manager = new ObstacleManager();
    manager.activeEvent = fakeEvent([{ x: 500, y: 300, type }], 100);
    const obstacle = manager.activeEvent.heads[0];
    const ctx = new FakeContext();

    manager.update(0.1, 12, 300);
    const [hitbox] = manager.hitboxes();
    manager.draw(ctx, {
      dodgeObstacles: Object.fromEntries(DODGE_OBSTACLE_TYPES.map((registered) => [
        registered.assetKey,
        image(registered.assetKey)
      ]))
    });

    assert.equal(obstacle.obstacleTypeId, type.id);
    assert.equal(obstacle.assetKey, type.assetKey);
    assert.equal(hitbox.width, obstacle.collisionWidth * obstacle.hitboxScaleX);
    assert.equal(hitbox.height, obstacle.collisionHeight * obstacle.hitboxScaleY);
    assert.equal(ctx.drawnImage.name, type.assetKey);
    assert.equal(ctx.drawnWidth, type.render.width);
    assert.equal(ctx.drawnHeight, type.render.height);
  }
});

test("noodle-man scale and alpha-derived collision remain unchanged", () => {
  const obstacle = createDodgeObstacle(420, obstacleRowCenter(3), Math.random, NOODLE_MAN_TYPE, { row: 3 });
  const expectedHeight = STANDARD_SWIMMER_VISIBLE_ALPHA_HEIGHT / (NOODLE_MAN_TYPE.alpha.height / NOODLE_MAN_TYPE.source.height);
  const expectedWidth = expectedHeight * (NOODLE_MAN_TYPE.source.width / NOODLE_MAN_TYPE.source.height);

  assertAlmostEqual(obstacle.width, expectedWidth);
  assertAlmostEqual(obstacle.height, expectedHeight);
  assertAlmostEqual(
    obstacle.collisionWidth,
    expectedWidth * (NOODLE_MAN_TYPE.alpha.width / NOODLE_MAN_TYPE.source.width)
  );
  assertAlmostEqual(
    obstacle.collisionHeight,
    STANDARD_SWIMMER_VISIBLE_ALPHA_HEIGHT
  );
  assert.equal(obstacle.hitboxScaleX, 0.58);
  assert.equal(obstacle.hitboxScaleY, 0.58);
});

test("each dodge obstacle preserves its configured source aspect ratio", () => {
  const expectedAspects = new Map([
    ["head", 1448 / 1086],
    ["noodle-girl", 1448 / 1086],
    ["noodle-man", 1672 / 941],
    ["scuba-man", 1536 / 1024],
    ["tube-girl", 1254 / 1254],
    ["tube-woman", 1536 / 1024]
  ]);

  for (const type of DODGE_OBSTACLE_TYPES) {
    const obstacle = createDodgeObstacle(400, 300, Math.random, type);
    assertAlmostEqual(obstacle.width / obstacle.height, expectedAspects.get(type.id));
  }
});

test("each dodge obstacle type carries its own collision configuration", () => {
  const head = createDodgeObstacle(400, 300, Math.random, HEAD_TYPE);
  const noodleMan = createDodgeObstacle(400, 300, Math.random, NOODLE_MAN_TYPE);
  const scubaMan = createDodgeObstacle(400, 300, Math.random, SCUBA_MAN_TYPE);
  const tubeWoman = createDodgeObstacle(400, 300, Math.random, TUBE_WOMAN_TYPE);

  assert.notDeepEqual(
    {
      width: head.collisionWidth,
      height: head.collisionHeight,
      scaleX: head.hitboxScaleX,
      scaleY: head.hitboxScaleY
    },
    {
      width: tubeWoman.collisionWidth,
      height: tubeWoman.collisionHeight,
      scaleX: tubeWoman.hitboxScaleX,
      scaleY: tubeWoman.hitboxScaleY
    }
  );
  assert.notEqual(noodleMan.width, scubaMan.width);
  assert.notEqual(noodleMan.collisionWidth, scubaMan.collisionWidth);
});

test("riser progress is deterministic from the fixed horizontal route", () => {
  const first = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2), Math.random, SCUBA_MAN_TYPE, { row: 2 });
  const second = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2), Math.random, SCUBA_MAN_TYPE, { row: 2 });

  placeAtRouteProgress(first, midpoint(SCUBA_MAN_TYPE.presentation.startRouteProgress, SCUBA_MAN_TYPE.presentation.endRouteProgress));
  placeAtRouteProgress(second, midpoint(SCUBA_MAN_TYPE.presentation.startRouteProgress, SCUBA_MAN_TYPE.presentation.endRouteProgress));

  assertAlmostEqual(obstacleRiseProgress(first), 0.5);
  assertAlmostEqual(obstacleRiseProgress(second), 0.5);
  assert.deepEqual(obstacleRenderPresentation(first), obstacleRenderPresentation(second));
});

test("riser remains hidden until the configured start route progress", () => {
  const obstacle = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2), Math.random, SCUBA_MAN_TYPE, { row: 2 });

  placeAtRouteProgress(obstacle, SCUBA_MAN_TYPE.presentation.startRouteProgress - 0.001);

  assert.equal(obstacleRiseProgress(obstacle), 0);
  assert.equal(obstacleCollisionActive(obstacle), false);
  assert.equal(obstacleRenderPresentation(obstacle).visibleRatio, 0);
});

test("riser rise progress is zero at the start threshold and one at the end threshold", () => {
  const obstacle = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2), Math.random, SCUBA_MAN_TYPE, { row: 2 });

  placeAtRouteProgress(obstacle, SCUBA_MAN_TYPE.presentation.startRouteProgress);
  assert.equal(obstacleRiseProgress(obstacle), 0);

  placeAtRouteProgress(obstacle, SCUBA_MAN_TYPE.presentation.endRouteProgress);
  assert.equal(obstacleRiseProgress(obstacle), 1);
  assert.equal(obstacleRenderPresentation(obstacle).assetKey, "dodge-scuba-man-water");
});

test("riser starts fully hidden and switches cleanly to the surfaced asset", () => {
  const obstacle = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2), Math.random, SCUBA_MAN_TYPE, { row: 2 });
  const start = obstacleRenderPresentation(obstacle);

  assert.equal(obstacleRiseProgress(obstacle), 0);
  assert.equal(start.assetKey, "dodge-scuba-man-riser");
  assert.equal(start.visibleRatio, 0);
  assert.equal(start.clipHeight, obstacle.height);
  assert.equal(start.offsetY, obstacle.height);

  placeAtRouteProgress(obstacle, SCUBA_MAN_TYPE.presentation.endRouteProgress);
  const surfaced = obstacleRenderPresentation(obstacle);

  assert.equal(obstacleRiseProgress(obstacle), 1);
  assert.equal(surfaced.assetKey, "dodge-scuba-man-water");
  assert.equal(surfaced.clipHeight, obstacle.height);
  assert.equal(surfaced.offsetY, 0);
});

test("intermediate riser drawing clips the emerging swimmer without moving the logical row", () => {
  const obstacle = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(1), Math.random, SCUBA_MAN_TYPE, { row: 1 });
  placeAtRouteProgress(obstacle, midpoint(SCUBA_MAN_TYPE.presentation.startRouteProgress, SCUBA_MAN_TYPE.presentation.endRouteProgress));
  const manager = new ObstacleManager();
  const ctx = new FakeContext();
  manager.activeEvent = fakeEventFromObstacles([obstacle]);

  manager.draw(ctx, {
    dodgeObstacles: {
      "dodge-scuba-man-riser": image("dodge-scuba-man-riser"),
      "dodge-scuba-man-water": image("dodge-scuba-man-water")
    }
  });

  assert.equal(obstacle.y, obstacleRowCenter(1));
  assert.equal(ctx.drawnImage.name, "dodge-scuba-man-riser");
  assertAlmostEqual(ctx.clipRect.height, obstacle.height);
  assertAlmostEqual(ctx.drawnY, ctx.clipRect.y + obstacle.height * 0.5);
  assert.equal(ctx.drawnX + ctx.drawnWidth / 2, obstacle.x);
});

test("riser final presentation matches established surfaced scuba geometry", () => {
  const obstacle = createDodgeObstacle(420, obstacleRowCenter(3), Math.random, SCUBA_MAN_TYPE, { row: 3 });
  const manager = new ObstacleManager();
  const ctx = new FakeContext();
  manager.activeEvent = fakeEventFromObstacles([obstacle]);

  manager.draw(ctx, {
    dodgeObstacles: {
      "dodge-scuba-man-riser": image("dodge-scuba-man-riser"),
      "dodge-scuba-man-water": image("dodge-scuba-man-water")
    }
  });

  assert.equal(obstacleRenderPresentation(obstacle).assetKey, "dodge-scuba-man-water");
  assert.equal(ctx.drawnImage.name, "dodge-scuba-man-water");
  assert.equal(ctx.drawnX + ctx.drawnWidth / 2, obstacle.x);
  assert.equal(ctx.drawnY + ctx.drawnHeight / 2, obstacle.y);
  assert.equal(dodgeObstacleVisibleBounds(obstacle).height, STANDARD_SWIMMER_VISIBLE_ALPHA_HEIGHT);
});

test("riser does not change logical row, y, horizontal trajectory, or speed", () => {
  const manager = new ObstacleManager();
  const obstacle = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(4), Math.random, SCUBA_MAN_TYPE, { row: 4 });
  manager.activeEvent = fakeEventFromObstacles([obstacle], 200);

  manager.update(0.25, 10, 300);

  assert.equal(obstacle.row, 4);
  assert.equal(obstacle.y, obstacleRowCenter(4));
  assert.equal(obstacle.x, CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING - 50);
  assert.equal(manager.activeEvent.speed, 200);
});

test("riser hitbox is absent before the collision threshold and normal after it", () => {
  const manager = new ObstacleManager();
  const obstacle = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2), Math.random, SCUBA_MAN_TYPE, { row: 2 });
  manager.activeEvent = fakeEventFromObstacles([obstacle]);

  placeAtRiseProgress(obstacle, 0.84);
  assert.equal(obstacleCollisionActive(obstacle), false);
  assert.deepEqual(manager.hitboxes(), []);

  placeAtRiseProgress(obstacle, 0.85);
  assert.equal(obstacleCollisionActive(obstacle), true);
  assert.deepEqual(manager.hitboxes(), [
    centeredTestRect(
      obstacle.x,
      obstacle.y,
      obstacle.collisionWidth * obstacle.hitboxScaleX,
      obstacle.collisionHeight * obstacle.hitboxScaleY
    )
  ]);
});

test("hidden riser still reserves placement and row release state", () => {
  const hidden = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2), Math.random, SCUBA_MAN_TYPE, { row: 2 });
  const candidate = fakeEventFromObstacles([
    createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2), Math.random, HEAD_TYPE, { row: 2 })
  ]);

  assert.equal(obstacleRiseProgress(hidden), 0);
  assert.equal(isHeadVisiblyPresent(hidden), true);
  assert.equal(isEventPlacementClear(candidate, [hidden]), false);
  assert.equal(rowIsReleased(2, [hidden], stageTuning(1)), false);
});

test("scuba riser scoring and pattern completion still occur exactly once", () => {
  const manager = new ObstacleManager();
  const completed = [];
  manager.activeEvent = createObstacleEvent({
    surferY: 300,
    elapsed: 0,
    pattern: PATTERN_BY_ID["stage2-long-weave"],
    difficultyStage: 2
  });
  manager.activeEvent.heads[0].x = CONFIG.OBSTACLE_SUBMERGE_END_X + 1;

  assert.equal(manager.update(0.1, 130, 300, {
    difficultyStage: 2,
    onNormalEventResolved: (event) => completed.push(event.patternId)
  }), 1);
  assert.deepEqual(completed, ["stage2-long-weave"]);
  assert.equal(manager.activeEvent, null);
  assert.equal(manager.update(0.1, 131, 300, {
    difficultyStage: 2,
    onNormalEventResolved: (event) => completed.push(event.patternId)
  }), 0);
  assert.deepEqual(completed, ["stage2-long-weave"]);
});

test("reset and repeated riser spawns do not share mutable rise state", () => {
  const manager = new ObstacleManager();
  const first = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2), Math.random, SCUBA_MAN_TYPE, { row: 2 });
  const second = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(3), Math.random, SCUBA_MAN_TYPE, { row: 3 });
  manager.activeEvent = fakeEventFromObstacles([first, second]);

  placeAtRouteProgress(first, first.presentation.endRouteProgress);

  assert.equal(obstacleRiseProgress(first), 1);
  assert.equal(obstacleRiseProgress(second), 0);

  manager.reset();
  const next = createDodgeObstacle(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, obstacleRowCenter(2), Math.random, SCUBA_MAN_TYPE, { row: 2 });
  manager.activeEvent = fakeEventFromObstacles([next]);

  assert.equal(obstacleRiseProgress(next), 0);
  assert.equal(manager.hitboxes().length, 0);
});

test("mixed obstacle groups respect the configured visual gap", () => {
  const head = createDodgeObstacle(400, 300, Math.random, HEAD_TYPE);
  const tubeWoman = createDodgeObstacle(
    400,
    300,
    Math.random,
    TUBE_WOMAN_TYPE
  );
  const clearTubeWoman = { ...tubeWoman, x: tubeWoman.x + head.width + tubeWoman.width };

  assert.equal(isEventPlacementClear(fakeEventFromObstacles([head, tubeWoman])), false);
  assert.equal(isEventPlacementClear(fakeEventFromObstacles([head, clearTubeWoman])), true);
});

test("mixed groups still reject impossible walls", () => {
  const surferY = midpoint(CONFIG.SURF_BOUNDS.top, CONFIG.SURF_BOUNDS.bottom);
  const playerX = CONFIG.SURF_BOUNDS.left + (CONFIG.SURF_BOUNDS.right - CONFIG.SURF_BOUNDS.left) * 0.35;
  const event = fakeEventFromObstacles([
    createDodgeObstacle(playerX + 1, surferY - 18, Math.random, HEAD_TYPE),
    createDodgeObstacle(playerX + 1, surferY, Math.random, NOODLE_GIRL_TYPE),
    createDodgeObstacle(playerX + 1, surferY + 18, Math.random, TUBE_GIRL_TYPE)
  ], 999);

  assert.equal(isEventFair(event, surferY, event.speed), false);
});

test("obstacle opacity is full before the submerge start", () => {
  assert.equal(obstacleOpacityForX(CONFIG.OBSTACLE_SUBMERGE_START_X + 40), 1);
  assert.equal(obstacleOpacityForX(CONFIG.OBSTACLE_SUBMERGE_START_X), 1);
});

test("obstacle opacity decreases between submerge start and end", () => {
  const midpoint = (CONFIG.OBSTACLE_SUBMERGE_START_X + CONFIG.OBSTACLE_SUBMERGE_END_X) / 2;
  const opacity = obstacleOpacityForX(midpoint);

  assert.ok(opacity > 0);
  assert.ok(opacity < 1);
});

test("obstacle opacity reaches zero at the submerge end", () => {
  assert.equal(obstacleOpacityForX(CONFIG.OBSTACLE_SUBMERGE_END_X), 0);
  assert.equal(obstacleOpacityForX(CONFIG.OBSTACLE_SUBMERGE_END_X - 80), 0);
});

test("obstacle opacity is clamped between zero and one", () => {
  for (const x of [-500, 0, 249, 300, 390, 800, 1500]) {
    const opacity = obstacleOpacityForX(x);
    assert.ok(opacity >= 0);
    assert.ok(opacity <= 1);
  }
});

test("submerge sink is slight and reaches the configured amount", () => {
  assert.equal(obstacleSinkForX(CONFIG.OBSTACLE_SUBMERGE_START_X), 0);
  assert.equal(obstacleSinkForX(CONFIG.OBSTACLE_SUBMERGE_END_X), CONFIG.OBSTACLE_SUBMERGE_SINK_PX);
});

test("an individual submerged head is counted as dodged only once", () => {
  const manager = new ObstacleManager();
  manager.activeEvent = fakeEvent([{ x: CONFIG.OBSTACLE_SUBMERGE_END_X + 1, y: 300 }], 20);

  assert.equal(manager.update(0.1, 12, 300), 1);
  assert.equal(manager.activeEvent, null);
  assert.equal(manager.update(0.1, 12, 300), 0);
});

test("a submerged noodle-man dodge is scored exactly once", () => {
  const manager = new ObstacleManager();
  manager.activeEvent = createObstacleEvent({
    surferY: 300,
    elapsed: 0,
    pattern: PATTERN_BY_ID["stage2-sweeping-staircase"],
    difficultyStage: 2
  });
  manager.activeEvent.heads[0].x = CONFIG.OBSTACLE_SUBMERGE_END_X + 1;

  assert.equal(manager.update(0.1, 130, 300, { difficultyStage: 2 }), 1);
  assert.equal(manager.activeEvent, null);
  assert.equal(manager.update(0.1, 131, 300, { difficultyStage: 2 }), 0);
});

test("a fully submerged head is no longer collision-active", () => {
  const manager = new ObstacleManager();
  manager.activeEvent = fakeEvent([{ x: CONFIG.OBSTACLE_SUBMERGE_END_X, y: 300 }]);
  manager.activeEvent.heads[0].resolved = true;
  manager.activeEvent.heads[0].counted = true;

  assert.deepEqual(manager.hitboxes(), []);
});

test("a double event remains active until both heads are resolved", () => {
  const manager = new ObstacleManager();
  manager.activeEvent = fakeEvent([
    { x: CONFIG.OBSTACLE_SUBMERGE_END_X + 1, y: 280 },
    { x: CONFIG.OBSTACLE_SUBMERGE_START_X, y: 340 }
  ], 20);

  assert.equal(manager.update(0.1, 20, 300), 1);
  assert.notEqual(manager.activeEvent, null);

  manager.activeEvent.heads[1].x = CONFIG.OBSTACLE_SUBMERGE_END_X + 1;
  assert.equal(manager.update(0.1, 20, 300), 1);
  assert.equal(manager.activeEvent, null);
});

test("event completion permits the next spawn cycle", () => {
  const manager = new ObstacleManager();
  manager.activeEvent = fakeEvent([{ x: CONFIG.OBSTACLE_SUBMERGE_END_X + 1, y: 300 }], 20);

  manager.update(0.1, 20, 300);

  assert.equal(canSpawnNextEvent(manager.activeEvent), true);
  assert.ok(manager.spawnTimer >= CONFIG.SPAWN_DELAY_END.min);
  assert.ok(manager.spawnTimer <= CONFIG.SPAWN_DELAY_START.max);
});

test("normal spawn timer freezes when encounters pause spawns", () => {
  const manager = new ObstacleManager();
  manager.spawnTimer = 0.1;

  assert.equal(manager.update(0.2, 10, 300, { pauseSpawns: true }), 0);

  assert.equal(manager.activeEvent, null);
  assert.equal(manager.spawnTimer, 0.1);
});

test("encounter obstacles use the shared obstacle collision path", () => {
  const manager = new ObstacleManager();
  manager.addObstacle({
    assetKey: "bottle",
    x: 500,
    y: 300,
    width: 60,
    height: 30,
    speed: 100,
    collisionScale: 0.5
  });

  assert.deepEqual(manager.hitboxes(), [
    {
      x: 485,
      y: 292.5,
      width: 30,
      height: 15
    }
  ]);
});

test("configured spawn delays remain valid", () => {
  assert.ok(CONFIG.SPAWN_DELAY_START.min <= CONFIG.SPAWN_DELAY_START.max);
  assert.ok(CONFIG.SPAWN_DELAY_END.min <= CONFIG.SPAWN_DELAY_END.max);
  assert.ok(spawnDelayForTime(0, () => 0) >= CONFIG.SPAWN_DELAY_START.min);
  assert.ok(spawnDelayForTime(999, () => 1) <= CONFIG.SPAWN_DELAY_END.max);
});

test("initial spawn-delay range is faster at the beginning of the game", () => {
  assert.equal(spawnDelayForTime(0, () => 0), 0.8);
  assert.equal(spawnDelayForTime(0, () => 1), 1.4);
});

function assertHeadInsideBounds(head) {
  assert.ok(head.y - head.height / 2 >= CONFIG.SURF_BOUNDS.top);
  assert.ok(head.y + head.height / 2 <= CONFIG.SURF_BOUNDS.bottom);
}

function fixedRandom(values) {
  let index = 0;
  return () => {
    const value = values[index % values.length];
    index += 1;
    return value;
  };
}

function fakeEvent(heads, speed = CONFIG.OBSTACLE_START_SPEED) {
  return {
    type: heads.length === 1 ? "single" : "double",
    speed,
    threatening: true,
    collided: false,
    heads: heads.map((head) => createTestHead(head.x, head.y, head.type ?? HEAD_TYPE))
  };
}

function fakeEventFromObstacles(heads, speed = CONFIG.OBSTACLE_START_SPEED) {
  return {
    type: heads.length === 1 ? "single" : "double",
    speed,
    threatening: true,
    collided: false,
    heads
  };
}

function createTestHead(x, y, type = HEAD_TYPE) {
  return createDodgeObstacle(x, y, Math.random, type);
}

function midpoint(a, b) {
  return a + (b - a) / 2;
}

function assertAlmostEqual(actual, expected, epsilon = 1e-9) {
  assert.ok(Math.abs(actual - expected) <= epsilon, `${actual} did not equal ${expected}`);
}

function centeredTestRect(x, y, width, height) {
  return {
    x: x - width / 2,
    y: y - height / 2,
    width,
    height
  };
}

function placeAtRouteProgress(obstacle, progress) {
  obstacle.x = obstacle.routeStartX - (obstacle.routeStartX - obstacle.routeEndX) * progress;
}

function placeAtRiseProgress(obstacle, progress) {
  const start = obstacle.presentation.startRouteProgress;
  const end = obstacle.presentation.endRouteProgress;
  placeAtRouteProgress(obstacle, start + (end - start) * progress);
}

function maxSimultaneousSwimmers(pattern) {
  const counts = new Map();
  for (const obstacle of pattern.obstacles) {
    counts.set(obstacle.timeOffset, (counts.get(obstacle.timeOffset) ?? 0) + 1);
  }
  return Math.max(0, ...counts.values());
}

function sampleScheduledEvents() {
  const scheduler = new DeterministicObstacleScheduler();
  const events = [];
  for (let i = 0; i < 4; i += 1) {
    const event = scheduler.nextEvent({
      difficultyStage: 0,
      surferY: 300,
      activeHeads: []
    });
    events.push({
      patternId: event.patternId,
      heads: event.heads.map((head) => [head.obstacleTypeId, head.row, head.timeOffset])
    });
  }
  return events;
}

function sampleStageEvents(stage, count) {
  const scheduler = new DeterministicObstacleScheduler();
  const events = [];
  for (let i = 0; i < count; i += 1) {
    const event = scheduler.nextEvent({
      difficultyStage: stage,
      surferY: 300,
      activeHeads: []
    });
    events.push({
      patternId: event.patternId,
      heads: event.heads.map((head) => [head.obstacleTypeId, head.assetKey, head.row, head.timeOffset])
    });
  }
  return events;
}

function resolveActiveEvent(manager) {
  for (const head of manager.activeEvent.heads) {
    head.x = CONFIG.OBSTACLE_SUBMERGE_END_X + 1;
  }
}

function createBlockingSpawnColumn() {
  const heads = [];
  for (let y = CONFIG.SURF_BOUNDS.top; y <= CONFIG.SURF_BOUNDS.bottom; y += 10) {
    heads.push(createTestHead(CONFIG.WIDTH + CONFIG.SPAWN_X_PADDING, y));
  }
  return heads;
}

function row2VisibleWidth() {
  return dodgeObstacleVisibleBounds(createDodgeObstacle(0, obstacleRowCenter(2), Math.random, HEAD_TYPE, { row: 2 })).width;
}

function largestVisibleOpening(obstacles) {
  const occupied = obstacles
    .map(dodgeObstacleVisibleBounds)
    .sort((a, b) => a.top - b.top);
  let largest = 0;
  let cursor = CONFIG.SURF_BOUNDS.top;

  for (const bounds of occupied) {
    largest = Math.max(largest, bounds.top - cursor);
    cursor = Math.max(cursor, bounds.bottom);
  }

  return Math.max(largest, CONFIG.SURF_BOUNDS.bottom - cursor);
}

async function sourceFilePaths() {
  const dirs = ["src"];
  const files = [];

  for (const dir of dirs) {
    const entries = await readdir(new URL(`../${dir}/`, import.meta.url), {
      recursive: true,
      withFileTypes: true
    });
    for (const entry of entries) {
      if (entry.isFile() && entry.name.endsWith(".js")) {
        files.push(new URL(`../${dir}/${entry.name}`, import.meta.url));
      }
    }
  }

  files.push(new URL("../index.html", import.meta.url));
  return files;
}

function image(name) {
  return { name };
}

class FakeContext {
  save() {}

  restore() {}

  beginPath() {}

  rect(x, y, width, height) {
    this.clipRect = { x, y, width, height };
  }

  clip() {
    this.clipped = true;
  }

  drawImage(image, x, y, width, height) {
    this.drawnImage = image;
    this.drawnX = x;
    this.drawnY = y;
    this.drawnWidth = width;
    this.drawnHeight = height;
  }
}
