export const VERSION = "v0.4.1";

const SURFER_DISPLAY_HEIGHT = 140;
const SURFER_DISPLAY_WIDTH = 1199 * (SURFER_DISPLAY_HEIGHT / 1312);

export const CONFIG = {
  DEBUG: false,
  DEBUG_START_STAGE: null,
  DEBUG_REDUCED_SPEED_MULTIPLIER: 1,
  WIDTH: 1024,
  HEIGHT: 576,
  SURFER_DISPLAY_WIDTH,
  SURFER_DISPLAY_HEIGHT,
  SURFER_SPEED: 260,
  SURFER_HITBOX_SCALE_X: 0.6,
  SURFER_HITBOX_SCALE_Y: 0.64,
  SURF_BOUNDS: {
    left: 120,
    right: 650,
    top: 185,
    bottom: 500
  },
  OBSTACLE_ROW_COUNT: 6,
  DEBUG_OBSTACLE_ROWS: false,
  PATTERN_VALIDATION_TIMESTEP_SECONDS: 0.08,
  PATTERN_VALIDATION_Y_STEP: 6,
  PATTERN_VALIDATION_REACTION_SECONDS: 0.18,
  PATTERN_VALIDATION_PADDING: 6,
  PATTERN_OVERLAP_MIN_DIFFICULTY: 0.72,
  HEAD_DISPLAY_WIDTH: 70,
  HEAD_DISPLAY_HEIGHT: 70 / 1.5,
  HEAD_HITBOX_SCALE_X: 0.6,
  HEAD_HITBOX_SCALE_Y: 0.6,
  OBSTACLE_START_SPEED: 180,
  OBSTACLE_MAX_SPEED: 420,
  DIFFICULTY_RAMP_SECONDS: 180,
  SPAWN_X_PADDING: 60,
  // Extra rendered-bounds padding, in pixels, required between visible head sprites.
  HEAD_MIN_VISUAL_GAP_X: 18,
  HEAD_MIN_VISUAL_GAP_Y: 18,
  HEAD_SPAWN_PLACEMENT_RETRIES: 30,
  EVENT_CLEAR_X: 80,
  OBSTACLE_SUBMERGE_START_X: 390,
  OBSTACLE_SUBMERGE_END_X: 250,
  OBSTACLE_SUBMERGE_SINK_PX: 10,
  SINGLE_WEIGHT_START: 0.8,
  SINGLE_WEIGHT_END: 0.55,
  DOUBLE_WEIGHT_MAX: 0.45,
  SPAWN_DELAY_START: {
    min: 0.8,
    max: 1.4
  },
  SPAWN_DELAY_END: {
    min: 0.6,
    max: 1.1
  },
  WAVE_FRAME_MS_MIN: 120,
  WAVE_FRAME_MS_MAX: 160,
  ENCOUNTERS_ENABLED: true,
  FIRST_ENCOUNTER_TIME_MS: 45000,
  FISHERMAN_ENTRY_SPEED: 170,
  FISHERMAN_EXIT_SPEED: 220,
  FISHERMAN_STOP_X: 810,
  FISHERMAN_DISPLAY_WIDTH: 210,
  FISHERMAN_LANE_SPEED: 150,
  FISHERMAN_LANE_SNAP_DISTANCE: 6,
  FISHERMAN_THROW_INTERVAL_MIN_MS: 900,
  FISHERMAN_THROW_INTERVAL_MAX_MS: 1400,
  FISHERMAN_THROW_WINDUP_MS: 300,
  FISHERMAN_POST_THROW_DELAY_MS: 200,
  FISHERMAN_PROJECTILE_ARC_HEIGHT: 64,
  FISHERMAN_PROJECTILE_DURATION_MS: 520,
  FISHERMAN_THROWABLE_SPEED: 310,
  FISHERMAN_WALLET_SPEED_MULTIPLIER: 0.8,
  FISHERMAN_WALLET_LOSS_PAUSE_SECONDS: 2,
  FISHERMAN_WALLET_LOSS_EXIT_SPEED: 80,
  COOLER_ENCOUNTER_TIME_MS: 105000,
  COOLER_BOAT_ENTRY_SPEED: 170,
  COOLER_BOAT_VERTICAL_SPEED: 171,
  COOLER_ATTACK_POSITIONS: {
    top: 210,
    bottom: 475
  },
  COOLER_ITEM_RELEASE_INTERVAL_SECONDS: 0.16,
  COOLER_ITEMS_PER_WAVE: 12,
  COOLER_PROTECTED_GAP_SIZE: 126,
  COOLER_BETWEEN_WAVE_PAUSE_SECONDS: 0.55,
  COOLER_FINAL_PRE_EXIT_PAUSE_SECONDS: 0.75,
  COOLER_EXIT_SPEED: 220,
  COOLER_POST_ENCOUNTER_GRACE_SECONDS: 0.9,
  COOLER_DROP_DURATION_SECONDS: 0.18,
  COOLER_DROP_DISTANCE_X: 74,
  COOLER_DROP_DISTANCE_Y: 34,
  WIPEOUT_SECONDS: 1,
  SCORE_TIME_MULTIPLIER: 100,
  SCORE_DODGE_VALUE: 500,
  STORAGE_KEY: "surf-game-v0.4.1-records"
};

CONFIG.ENCOUNTER_SEQUENCE = [
  {
    id: "angry-fisherman",
    startTimeMs: CONFIG.FIRST_ENCOUNTER_TIME_MS,
    difficultyStageOnComplete: 1
  },
  {
    id: "angry-fisherman-cooler",
    startTimeMs: CONFIG.COOLER_ENCOUNTER_TIME_MS,
    difficultyStageOnComplete: 2,
    postEncounterGraceSeconds: CONFIG.COOLER_POST_ENCOUNTER_GRACE_SECONDS
  }
];

export function encounterConfig(id) {
  return CONFIG.ENCOUNTER_SEQUENCE.find((encounter) => encounter.id === id) ?? null;
}
