export const VERSION = "v0.7.0";

const SURFER_DISPLAY_HEIGHT = 140;
const SURFER_DISPLAY_WIDTH = 1199 * (SURFER_DISPLAY_HEIGHT / 1312);

export const CONFIG = {
  DEBUG: true,
  DEVELOPER_CONTROLS: true,
  DEBUG_START_STAGE: null,
  DEBUG_REDUCED_SPEED_MULTIPLIER: 1,
  WIDTH: 1024,
  HEIGHT: 576,
  SURFER_DISPLAY_WIDTH,
  SURFER_DISPLAY_HEIGHT,
  SURFER_MOVEMENT_FOOTPRINT: [
    { x: -65, y: 37 },
    { x: -64, y: -5 },
    { x: -41, y: -61 },
    { x: 1, y: -71 },
    { x: 35, y: -56 },
    { x: 52, y: -42 },
    { x: 64, y: 54 },
    { x: 56, y: 62 },
    { x: -22, y: 64 },
    { x: -58, y: 57 }
  ],
  SURFER_SPEED: 260,
  SURFER_HITBOX_SCALE_X: 0.6,
  SURFER_HITBOX_SCALE_Y: 0.64,
  SURF_BOUNDS: {
    left: 120,
    right: 710,
    top: 185,
    bottom: 500
  },
  DEBUG_SURFER_BOUNDS: false,
  SURFER_PLAYFIELD_BOUNDARY: [
    { x: 160, y: 500 },
    { x: 180, y: 295 },
    { x: 292, y: 205 },
    { x: 401, y: 116 },
    { x: 588, y: 116 },
    { x: 650, y: 104 },
    { x: 710, y: 104 }
  ],
  OBSTACLE_ROW_COUNT: 6,
  DEBUG_OBSTACLE_ROWS: false,
  PATTERN_VALIDATION_TIMESTEP_SECONDS: 0.08,
  PATTERN_VALIDATION_Y_STEP: 6,
  PATTERN_VALIDATION_REACTION_SECONDS: 0.18,
  PATTERN_VALIDATION_PADDING: 6,
  PATTERN_OVERLAP_MIN_DIFFICULTY: 0.72,
  HEAD_DISPLAY_WIDTH: 70,
  HEAD_DISPLAY_HEIGHT: 70 / 1.5,
  HEAD_HITBOX_SCALE_X: 0.6,
  HEAD_HITBOX_SCALE_Y: 0.6,
  OBSTACLE_START_SPEED: 180,
  OBSTACLE_MAX_SPEED: 420,
  DIFFICULTY_RAMP_SECONDS: 180,
  SPAWN_X_PADDING: 60,
  // Extra rendered-bounds padding, in pixels, required between visible head sprites.
  HEAD_MIN_VISUAL_GAP_X: 18,
  HEAD_MIN_VISUAL_GAP_Y: 18,
  HEAD_SPAWN_PLACEMENT_RETRIES: 30,
  EVENT_CLEAR_X: 80,
  OBSTACLE_SUBMERGE_START_X: 390,
  OBSTACLE_SUBMERGE_END_X: 250,
  OBSTACLE_SUBMERGE_SINK_PX: 10,
  ANTI_CAMP_PASSIVE_PASS_THRESHOLD: 2,
  ANTI_CAMP_MOVEMENT_THRESHOLD: 42,
  ANTI_CAMP_TELEGRAPH_SECONDS: 0.65,
  ANTI_CAMP_AIRBORNE_SPEED: 520,
  ANTI_CAMP_AIRBORNE_FRAME_SECONDS: 0.12,
  ANTI_CAMP_WATER_SPEED: 210,
  ANTI_CAMP_LAUNCH_OFFSET_X: 320,
  ANTI_CAMP_LANDING_OFFSET_X: 0,
  ANTI_CAMP_ARC_HEIGHT: 86,
  ANTI_CAMP_DISPLAY_WIDTH: 76,
  ANTI_CAMP_HITBOX_SCALE_X: 0.62,
  ANTI_CAMP_HITBOX_SCALE_Y: 0.54,
  ANTI_CAMP_RETRIGGER_COOLDOWN_SECONDS: 1.1,
  SINGLE_WEIGHT_START: 0.8,
  SINGLE_WEIGHT_END: 0.55,
  DOUBLE_WEIGHT_MAX: 0.45,
  SPAWN_DELAY_START: {
    min: 0.8,
    max: 1.4
  },
  SPAWN_DELAY_END: {
    min: 0.6,
    max: 1.1
  },
  WAVE_FRAME_MS_MIN: 120,
  WAVE_FRAME_MS_MAX: 160,
  ENCOUNTERS_ENABLED: true,
  FIRST_ENCOUNTER_TIME_MS: 45000,
  FISHERMAN_ENTRY_SPEED: 170,
  FISHERMAN_EXIT_SPEED: 220,
  FISHERMAN_STOP_X: 860,
  FISHERMAN_DISPLAY_WIDTH: 210,
  FISHERMAN_LANE_SPEED: 150,
  FISHERMAN_LANE_SNAP_DISTANCE: 6,
  FISHERMAN_THROW_INTERVAL_MIN_MS: 900,
  FISHERMAN_THROW_INTERVAL_MAX_MS: 1400,
  FISHERMAN_THROW_WINDUP_MS: 300,
  FISHERMAN_POST_THROW_DELAY_MS: 200,
  FISHERMAN_PROJECTILE_ARC_HEIGHT: 64,
  FISHERMAN_PROJECTILE_DURATION_MS: 520,
  FISHERMAN_THROWABLE_SPEED: 310,
  FISHERMAN_WALLET_SPEED_MULTIPLIER: 0.8,
  FISHERMAN_WALLET_LOSS_PAUSE_SECONDS: 2,
  FISHERMAN_WALLET_LOSS_EXIT_SPEED: 80,
  COOLER_ENCOUNTER_TIME_MS: 105000,
  COOLER_BOAT_ENTRY_SPEED: 170,
  COOLER_BOAT_VERTICAL_SPEED: 171,
  COOLER_ATTACK_POSITIONS: {
    top: 210,
    bottom: 475
  },
  COOLER_ITEM_RELEASE_INTERVAL_SECONDS: 0.16,
  COOLER_ITEMS_PER_WAVE: 12,
  COOLER_PROTECTED_GAP_SIZE: 126,
  COOLER_BETWEEN_WAVE_PAUSE_SECONDS: 0.55,
  COOLER_FINAL_PRE_EXIT_PAUSE_SECONDS: 0.75,
  COOLER_EXIT_SPEED: 220,
  COOLER_POST_ENCOUNTER_GRACE_SECONDS: 0.9,
  COOLER_DROP_DURATION_SECONDS: 0.18,
  COOLER_DROP_DISTANCE_X: 74,
  COOLER_DROP_DISTANCE_Y: 34,
  COOLER_TOSS_HOLD_SECONDS: 0.45,
  COOLER_TOSS_WINDUP_SECONDS: 0.3,
  COOLER_TOSS_POST_THROW_SECONDS: 0.35,
  COOLER_TOSS_PROJECTILE_DURATION_SECONDS: 0.78,
  COOLER_TOSS_ARC_HEIGHT: 82,
  COOLER_TOSS_LANDING_ROW: 3,
  COOLER_TOSS_ATTACK_COOLER_WIDTH: 96,
  COOLER_TOSS_WATER_COOLER_WIDTH: 112,
  WIPEOUT_SECONDS: 1,
  SCORE_TIME_MULTIPLIER: 100,
  SCORE_DODGE_VALUE: 500,
  STORAGE_KEY: "surf-game-v0.7.0-records"
};

CONFIG.ENCOUNTER_SEQUENCE = [
  {
    id: "angry-fisherman",
    startTimeMs: CONFIG.FIRST_ENCOUNTER_TIME_MS,
    difficultyStageOnComplete: 1
  },
  {
    id: "angry-fisherman-cooler",
    startTimeMs: CONFIG.COOLER_ENCOUNTER_TIME_MS,
    difficultyStageOnComplete: 2,
    postEncounterGraceSeconds: CONFIG.COOLER_POST_ENCOUNTER_GRACE_SECONDS
  },
  {
    id: "angry-fisherman-cooler",
    startTimeMs: 138000,
    difficultyStageOnComplete: 2,
    handoffToNext: true,
    immediateSuccessorId: "angry-fisherman-cooler-toss"
  },
  {
    id: "angry-fisherman-cooler-toss",
    difficultyStageOnComplete: 2
  }
];

export function encounterConfig(id) {
  return CONFIG.ENCOUNTER_SEQUENCE.find((encounter) => encounter.id === id) ?? null;
}

export function developerControlsEnabled(config = CONFIG) {
  return config.DEVELOPER_CONTROLS === true;
}
